### ISSUE TITLE
TechReborn cables not connecting to RF Consumer

### ISSUE THREAD

**Issue by Xalcon** [Xalcon/EnergyConverters#10]
Currently, TechReborn cables dont connect to consumers, which means RF consumers only work on generators, but not through cables or energy storages like the MFSU.

**Comment by Xalcon** [comment]
Looks like we need to implement the IEnergyInterfaceTile interface from RebornCore, so cables connect to our block.
https://github.com/TechReborn/TechReborn/blob/1.11.2/src/main/java/techreborn/parts/powerCables/CableMultipart.java#L253-L255

**Comment by kenijey** [comment]
glad to see this! hope be fixed.

**Comment by kenijey** [comment]
i appreciate ur work (Y)

**Comment by Xalcon** [comment]
i only did some minor testing, i'll release an alpha version and then work on porting these changing to the 1.11.2 version

**Comment by kenijey** [comment]
hey ah, please see this
https://github.com/TechReborn/RebornCore/commit/60a6982fde4b940797b5f5dc77a68552f5f9f499
https://github.com/modmuss50/Fluxed-Redstone/issues/24#event-1087713880

**Comment by Xalcon** [comment]
Thanks for the info - this only has an effect when directly connecting to machines. Cables work differently, therefore implementing the interface is still required for the cables to connect to a consumer or producer.

Additionally, this fix is currently only applied to the 1.11.2 version. We will see if this will be fixed in 1.10.2 as well and if it has any impact on the implementation in EnergyConverters.

All in all, the support for TechReborn is done, might be buggy, but we will see that when I can do my playtesting.
I hope I can release an update for EnergyConverters later today, but since minecraft forge's maven repo is currently unavailable, im not able to build a new version at the moment.

**Comment by kenijey** [comment]
okay. btw i'm on 1.11.2 with forge 2298. get luck with! thanks a lot.

**Comment by kenijey** [comment]
we really need to connect techreborn cables to your converter. we need to use techreborn energy in other mods, or other mods energy in techreborn. it would be lovely.
