### ISSUE TITLE
Joule converter?

### ISSUE THREAD

**Issue by Trinsdar** [Xalcon/EnergyConverters#20]
I know that Mekinism supports rf and eu, but it would be useful for packs where those are disabled, therefore forcing one to use converters.

**Comment by Xalcon** [comment]
After checking the Mekanism source, I don't see the value in adding explicit support for Mekanism joules. Mekanism directly supports every major energy system except Buildcrafts MJ. The only reason, that might look appealing at first is the option to add lossy conversion between energy systems - but Mekanism also has support for this.

Therefore, I wont implement direct support for mekanism at this time; the indirect support that is already present should suffice.
