### ISSUE TITLE
MJ producer not showing

### ISSUE THREAD

**Issue by cad435** [Xalcon/EnergyConverters#21]
Hello,

I currently runing Buildcraft BuildCraft 7.99.12 with energyConverters 1.0.1.2 and the MJ-Producer/Consumer is not visible...

Not sure if its a Bug on your side or Buildcraft related, but i guess its from your mod..

cad435

**Comment by Vassterak** [comment]
Hi the block is disablet in this version You'll need the lates 1.11.2 because in 1.12.2 it's not done yet
