### ISSUE TITLE
Only FE and IC2 Producers/Consumers showing up.

### ISSUE THREAD

**Issue by mikolajkazmierczak** [Xalcon/EnergyConverters#22]
Just like in the title, no ohter are showing up, even though I have installed Mekanism and Industrial Craft 

Minecraft Version: 1.12.2
BuildCraft Version: 7.99.12
IC2 Version: 2.8.16-ex112
Mekanism Version: 9.4.1.326 (For Minecraft 1.12.1)
Energy Converters Version: 1.0.1.2

**Comment by goldjee** [comment]
+1

**Comment by Xalcon** [comment]
The Buildcraft conversion was disabled due to a change request from one of the buildcraft developers. I wasnt able to get around this, but if EnergyConverters is still being used, I'll consider updating Energy converts accordingly.
