### ISSUE TITLE
Cannot convert to/from RF

### ISSUE THREAD

**Issue by Raven2911b** [Xalcon/EnergyConverters#24]
First I tried it on minecraft 1.10.2. I can convert EU to RF/IF (immersive engineering) with no issues.  However, when using minecraft 1.12.2, I cannot convert in either direction Eu to RF or RF to EU.   The issue seems to be on the RF side.  When going from EU to RF, the bridge does hold a charge, but going RF to EU, the bridge is showing zero.  Is it possible that the forge version might be the issue? Currently runnign forge 14.23.1.2600

**Comment by Raven2911b** [comment]
No change with upgrading/downgrading forge versions.  Still can't convert to or from RF energy.

**Comment by Xalcon** [comment]
Make sure you are using the FE Producer/Consumer since RF is its very own API which is not supported by a lot of mods (atleast back then). Conversion is working just fine for me in my Dev world.
