### ISSUE TITLE
No BC Consumer

### ISSUE THREAD

**Issue by FirePlanetZA** [Xalcon/EnergyConverters#32]
Where is the BC Consumer in 1.12.1

**Comment by Xalcon** [comment]
The BC Consumer/Producers will be re-introduced once buildcraft leaves its alpha status. I have some working code available, so an update will be quick, assuming they dont change anything related to their energy system...

**Comment by krzysztofKKW** [comment]
Looking at their roadmap, it seems that it won't leave alpha for some time...
Their energy system should not change; the only thing that seems not to work is energy transfer cap on pipes.
Why can't you release appropriate build yet?

**Comment by CvoidWyvern** [comment]
Any chance something could be done temporally like putting a version with MJ producers/consumers up as alpha? I'm trying to find any mod for 1.12.2 that can do specifically FE->MJ, and modernconverter seems to be the only mod that does this rn, which has a bunch of other content I'd have to remove.

**Comment by Xalcon** [comment]
MJ support will be back in the next release.

**Comment by AlexIIL** [comment]
> Their energy system should not change; the only thing that seems not to work is energy transfer cap on pipes.

Just FYI the energy system will *completely* change before buildcraft even gets to beta status. Obviously there's no reason to remove it now but please keep in mind that what you've currently got might crash with the newer changes.

**Comment by Xalcon** [comment]
@AlexIIL thanks, i was expecting changes from the beginning hence why I didnt want to add buildcraft support for such a long time - but people started to edit the code and distribute modified jars in the comments of the curseforge project. It's not against the license to do so, but I'd rather have this feature officially enabled, for obvious reasons.

I'm sure people will open up issues when you change the API and my mod keeps crashing during gameplay :P

**Comment by AlexIIL** [comment]
Ok :)
