### ISSUE TITLE
IC2 Consimer not work with wires

### ISSUE THREAD

**Issue by Apollon-Theos** [Xalcon/EnergyConverters#36]
Only "next cell".
Wires support only IC2 Producer.

**Comment by Xalcon** [comment]
I'm unable to replicate the issue. The Consumer connects just fine to any of the IC2 cables

![image](https://user-images.githubusercontent.com/5042450/50928802-f36b8480-145b-11e9-9225-fff528d701d9.png)

Can you please provide more information? Forge and Mod versions and the a screenshot of your setup would be helpful.

**Comment by Apollon-Theos** [comment]
IC2 wires not connect to devices from other mods. 
I try transfer RF (and CF) to Consumer by Laser Wires from Actually Additions, but no.
I think, this can with Energy Converters, but only without wires between EnergySource and Consumer.
![2019-01-10_01 35 08](https://user-images.githubusercontent.com/46534073/50934683-700d5b80-147a-11e9-93ec-dcc7b6ae5eca.jpg)
![2019-01-10_01 43 25](https://user-images.githubusercontent.com/46534073/50934684-700d5b80-147a-11e9-9c7e-dccebc42bd89.jpg)
![2019-01-10_01 47 07](https://user-images.githubusercontent.com/46534073/50934686-700d5b80-147a-11e9-96c9-07ef47812c41.jpg)

**Comment by Apollon-Theos** [comment]
XNet work, but have problem with logic. Multiple sources with same priority not work together, if sources from one mod, same problems.

**Comment by Xalcon** [comment]
I'm actually not sure what you are trying to accomplish. This is not a bug since I cant control what other mods do. 
If you want to convert IC2 power to FE, connect any IC2 power source (i.e. a cable) to a IC2 consumer and connect the Actually Additions lasers to a FE producer. Do not use the RF Producer, Actually Additions does not support the CoFH RedstoneFlux API - only Forge Energy is supported. 

I really consider removing support for RF, people seem to confuse it a lot and most mods dont even support it.

**Comment by Apollon-Theos** [comment]
Thank you for a explanation. 
Industrial Foregoing work with RF, at my last picture Laser Wires connect to device with RF, with other mods this work. 
Maybe change skin for Consumers, add letters "RF", "FE", "EU" and "CF"  on red circle ?

**Comment by Xalcon** [comment]
I know that Industrial Foregoing does support RF - but you tried to transmit RF via the actually additions lasers (which only support FE).

Also, adding letters doesn't really do anything in my opinion - it's already in their block name. 

Last but not least: adding any specific energy name from a mod that either supports or directly uses the Forge Energy capability wouldn't make any sense. CF, µI, DF, Joule, etc. They may be their own thing but all of them directly support FE and I can't realisticly reflect that in a name or even a texture. Something that I could do would be adding an analysis item that tells the player which energy systems a specific block supports.

If you really need to know what block you have placed in a world, I suggest installing Waila (hwyla) or TOP.

**Comment by Apollon-Theos** [comment]
Thank you for you work and words
