### ISSUE TITLE
Client side crash on power transfer

### ISSUE THREAD

**Issue by Gaz492** [Xalcon/EnergyConverters#39]
Client side crash on power transfer, https://hastebin.com/qoxupiqohe

This specific issue can be solved by wrapping the for loop [here](https://github.com/Xalcon/EnergyConverters/blob/mc_1.12/src/main/java/net/xalcon/energyconverters/common/tiles/TileEntityProducerFe.java#L31) in an if statement containing !world.isRemote

Looking at the other classes for the other converters it seems that this issue could crop up there as well

**Comment by Xalcon** [comment]
Good catch. That should only be running on the logical server. Fix incoming.

**Comment by Xalcon** [comment]
fixed in 1.2.1
Should be available on curseforge in a few minutes.
