### ISSUE TITLE
Missing recipes for MJ consumer and producer

### ISSUE THREAD

**Issue by IamKayrox** [Xalcon/EnergyConverters#51]
I have installed Buildcraft Core and Buildcraft Builders only, however the recipes for the MJ consumer and producer are missing since they are still dependent of Buildcraft Energy as far as I can see in the source code

**Comment by Xalcon** [comment]
oh... yeah. I only search+replaced through the src folder and forgot the assets. Fix is coming.

**Comment by Xalcon** [comment]
Fixed in 1.3.3
~~Awaiting curseforge approval right now.~~ Available on curseforge and twitch.

**Comment by IamKayrox** [comment]
Cool, and thanks for making our lives easier
