### ISSUE TITLE
MJ energy consumer

### ISSUE THREAD

**Issue by AwAii19** [Xalcon/EnergyConverters#53]
MJ energy consumer consume 10K  RF/T all the time, whatever is plug behind. There is an other issue with the MJ energy producer, it will use 10k RT/T to power an Buildcraft distiller, a quarry or a pump.

**Comment by Xalcon** [comment]
~~To be honest, I don't see the problem.
The MJ Producer asks the surrounding tiles how much power they want and gives them that amount (assuming there is enough stored in the bridge). Once the internal buffers of the BC machines fill up (Quarries have a huge internal storage!), the power transmission stops automatically.
The thing is, none of the buildcraft pipes currently limit the amount of power that can be transmitted.~~
![image](https://user-images.githubusercontent.com/5042450/68617118-cf872e00-04c6-11ea-820b-d71c55a2bfd9.png)

~~Am I misunderstanding your issue? Could you elaborate? Your issue sounds like a bug report, but to me this looks like everything is working as intended.~~

Reading is hard. I thought you were talking about the producer, my bad. I was able to replicate your issue. The consumer just takes all the power it can get. My bad! I'll work on a fix asap!

**Comment by Xalcon** [comment]
I've uploaded the Version 1.3.5.23 to curseforge, should be available shortly. Can you report back if this issue is fixed for you using the new version?

**Comment by AwAii19** [comment]
Ok, i test on my side and the MJ energy consumer not longer consume 10K RF/T all the time. But the energy production seems to be not smooth, also we loose a large amount of energy during the conversion. i make some test and for 1 000 000 rf in input , you fine around 5000 rf in the output.
look what i do :

![image](https://user-images.githubusercontent.com/38087155/68621197-69eb6f80-04cf-11ea-804a-1e0634c32cd4.png)

**Comment by AwAii19** [comment]
I don't know if the buildcraft pipes are buggy or if the problem is the converter ?

**Comment by AwAii19** [comment]
checkout this values ;
![image](https://user-images.githubusercontent.com/38087155/68621447-175e8300-04d0-11ea-8803-8c1f548fc1d4.png)
They increase by the time when the pipes is used.

**Comment by AwAii19** [comment]
As the pipes are still developing, there must be problems due to the above energy limit.
as you showed me in your comments.

**Comment by Xalcon** [comment]
Thanks for those pictures. I think I've found an issue with my fix. Working on it.

**Comment by Xalcon** [comment]
Okay, good news. I think i got it this time. Version 1.3.6.24 is awaiting approval on curseforge and should be available shortly. Sorry for the inconvenience.
