### ISSUE TITLE
2500eu/t output

### ISSUE THREAD

**Issue by jorlyf** [Xalcon/EnergyConverters#57]
"IndustrialVoltage(4, 5, "iv"); // or is it infinite voltage? No idea D: its just IV in the wiki"

I have only output 2500eu/t.
What I can do to increase this value?

**Comment by Xalcon** [comment]
The output is limited by the energy bridges internal buffer size. By default this is equivalent to 10k FE, effectivly limiting it to 2500 EU output (1:4 conversion ratio). You can increase the energy bridges buffer size in the config, but keep in mind: If you break the energy bridge, the stored energy will be lost.

**Comment by jorlyf** [comment]
Thanks for your answer! You solved my question
