### ISSUE TITLE
FTB Ultimate Reloaded JEI Missing Fe Converters

### ISSUE THREAD

**Issue by ghost** [Xalcon/EnergyConverters#58]
as title says im on ftb ultimate reloaded server and fe producer and consumer is missing: [https://imgur.com/a/z6CD8rI](https://imgur.com/a/z6CD8rI)

**Comment by Xalcon** [comment]
As far as I know ftb ultimate reloaded removes and changes a lot of recipes and blocks. I doubt this is a bug but rather intended. Try using the RF producers/consumers instead.
