### ISSUE TITLE
small transfer

### ISSUE THREAD

**Issue by Invisible229** [Xalcon/EnergyConverters#63]
With the indatrial craft addon, the energy shell transfers energy relatively little, can more powerful transfers be added with multiple levels? the screenshot shows that this panel gives out a lot of energy, but when I connect the converter to the same wire, it explodes... Can I fix this?

![image](https://user-images.githubusercontent.com/84010901/154012084-60765bd2-cd0d-44cf-94fe-8b8fc56ba070.png)

I will use this wire and panel

![image](https://user-images.githubusercontent.com/84010901/154012246-068aa1f6-70bb-4e26-b509-c3724bd29568.png)
![image](https://user-images.githubusercontent.com/84010901/154012396-6dbd9bed-aa7a-4e8a-a205-fad1b3455559.png)

it will be an experience
1.
![image](https://user-images.githubusercontent.com/84010901/154014977-197ef99e-2a9b-4172-8496-9eaac3b88462.png)

2.
![image](https://user-images.githubusercontent.com/84010901/154015022-46e71f45-d9f7-4f7b-add1-3d305b54b476.png)

3.
![image](https://user-images.githubusercontent.com/84010901/154014905-d37eb7ee-6280-4b3e-b81a-6df3d991b054.png)

**Comment by Invisible229** [comment]
also found another unfinished development
![image](https://user-images.githubusercontent.com/84010901/154019896-eee0bc3a-6e73-4ef8-8fea-d982bdcbce5f.png)
![image](https://user-images.githubusercontent.com/84010901/154019953-40b5a949-e3cb-414b-8b95-ee4a6ee2def5.png)
![image](https://user-images.githubusercontent.com/84010901/154019991-d5b33835-54a5-455b-b4ca-b08245452c90.png)
![image](https://user-images.githubusercontent.com/84010901/154020029-07838d6d-3b62-4966-b966-63fc48dbcb1b.png)
generation and processing cannot exceed 10000/t

**Comment by Invisible229** [comment]
![image](https://user-images.githubusercontent.com/84010901/154020379-c14444c2-2a1e-40eb-99bb-89556231ade7.png)
sorry for the trouble, the question closed by itself

**Comment by Xalcon** [comment]
I know you solved this yourself, but this is intended behavior. The bridge has an internal limit of 10k energy units, which is also the transfer limit. It is possible to increase the limit in the config, but this is not a bug.
