### ISSUE TITLE
Will this be updated to 1.19.2? Also, can it support Zaps? (FTB Industrial Contraptions).

### ISSUE THREAD

**Issue by Lion4K** [Xalcon/EnergyConverters#64]

**Comment by Xalcon** [comment]
At the moment, an update is rather unlikely.
EnergyConverters was created to allow using buildcraft with easier options like IC2 and RF/FE based mods. Neither IC2 nor Buildcraft have received a stable public update. Alongside these, I receive frequent request to support different mods energy systems.

The reason why I've not done this yet is two fold:
* Updating from 1.12 is a major undertaking, it requires a full rewrite of the mod
* Most of the requested Mods either have their own way of converting from and to FE (which inherently makes EnergyConvertes less useful) or don't have a stable API to interact with their respective energy system. In addition to this, a lot of mods requested in the past didn't even survive one major Minecraft Version, so I'm not wasting time on learning how their system works if it is irrelevant a few weeks later.

Unfortunately, my private schedule is rather tight and I don't like developing mods that I don't use personally.

Also, keep in mind that those Mods have a certain balance in mind when they chose to go with their own energy system without any means to convert to other energy systems. This is especially true when they don't even have an API to facilitate addons and I no longer feel comfortable hacking stuff together to "just get it working", breaking mod balance in the process.

**Comment by Lion4K** [comment]
I understand.
Still, thanks for all your work!
